apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deploymentv2
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
        env: development
    spec:
      containers:
      - name: my-app
        image: gcr.io/testimages-269619/app:v2
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: my-app